POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "My first video",
    "description": "First video added",
    "duration": 150
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/ff1e4d7f-61d7-4829-8925-3bea532e7105
Content-Type: application/json

{
    "title": "My first video 001",
    "description": "First video added",
    "duration": 150
}