POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "My first video",
    "description": "First video added",
    "duration": 150
}

###
GET http://localhost:3333/videos

###
PUT http://localhost/3333/videos/5ca5330a-634f-4b4f-a6ca-a4573e06b013

{
    "title": "My first video",
    "description": "First video added",
    "duration": 150
}